### PR TITLE
Add a pc file generator module

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
I am worried I am learning CMake. I hope this ends soon >.<

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Please, beware that the new PC file may be different from previous versions.

It seems that previous versions modified include dirs in a way that may shadow other libraries (utils dir seemd to take precedence). Current PC file also lists all dependent libs.

**Comment by BatchDrake** [comment]
I am afraid this does not work for me:

```
(metalloid) % sudo make install
[sudo] contraseña para waldo: 
Consolidate compiler generated dependencies of target sigutils
[100%] Built target sigutils
Install the project...
-- Install configuration: "Debug"
CMake Error at cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/home/waldo/Documents/Desarrollo/sigutils/sigutils.pc": No such file or
  directory.


make: *** [Makefile:100: install] Error 1
```

**Comment by BatchDrake** [comment]
Additional info:

I usually create a subdirectory inside each CMake project I am building (e.g. `build`) so that I do not mix up project files with generated/compiled files. I believe this is a de facto standard for many people as well. Turns out `sigutils.pc` is created after all, but inside `build`:

```
(metalloid) % pwd
/home/waldo/Documents/Desarrollo/sigutils/build
(metalloid) % ls -l
total 408
drwxr-xr-x 3 waldo waldo   4096 abr 15 22:48 analysis/
-rw-r--r-- 1 waldo waldo  23061 abr 15 22:48 CMakeCache.txt
drwxr-xr-x 8 waldo waldo   4096 abr 15 22:48 CMakeFiles/
-rw-r--r-- 1 waldo waldo   7384 abr 15 22:48 cmake_install.cmake
-rw-r--r-- 1 waldo waldo  12132 abr 15 22:48 compile_commands.json
lrwxrwxrwx 1 waldo waldo     16 abr 15 22:48 libsigutils.so -> libsigutils.so.1*
-rwxr-xr-x 1 waldo waldo 328520 abr 15 22:48 libsigutils.so.0.1.0*
lrwxrwxrwx 1 waldo waldo     20 abr 15 22:48 libsigutils.so.1 -> libsigutils.so.0.1.0*
-rw-r--r-- 1 waldo waldo  26561 abr 15 22:48 Makefile
-rw-r--r-- 1 waldo waldo    415 abr 15 22:48 sigutils.pc
```

Maybe the only thing missing is the full path of the generated .pc file (under `${PROJECT_BINARY_DIR}`, I believe)

**Comment by BatchDrake** [comment]
I also realize that the version is wrong, but I believe that's my fault because I didn't pull the tags. Still, I would love that anyone building did not have to care about these small details.

**Comment by antoniovazquezblanco** [comment]
Nice debugging. I will try to fix that soon. 

About the versioning thing, I can provide a strict mode that tries if no version is found it fails instead of waning and forces you to enter a version as a parameter when configuring... Maybe we should talk about this in a separate issue...

**Comment by antoniovazquezblanco** [comment]
I hope it is now ok!

**Pull request merged**
